#pragma once

// TASKS #75: hot-expert placement - frequency-ranked whole-expert assignment of
// routed experts to meta members. Artifact generated by scripts/expert-placement.py
// from a #74 LLAMA_EXPERT_PROFILE histogram; enabled via
// LLAMA_META_EXPERT_PLACEMENT=<json> on tensor-split (meta) configs.
// Design + gates: docs/expert-placement-plan.md

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "ggml-cpp.h"

// mul_mat_id id meaning "this member owns no expert for this (token, k) pair":
// the backend skips the lane and leaves its dst rows zeroed. Required because a
// token's ids must be DISTINCT - see docs/expert-placement-plan.md section 5.
#define LLAMA_EXPERT_SLOT_SKIP (-1)

struct llama_expert_placement {
    std::string model_name; // informational, from the artifact

    uint32_t n_layer  = 0;
    uint32_t n_expert = 0;

    // per layer: hottest-first permutation; perm[il][k] = ORIGINAL expert id at
    // permuted position k. Empty vector for layers without placement (dense or
    // never-routed layers in the profile).
    std::vector<std::vector<int32_t> > perm;

    // informational: the expert byte shares the artifact was generated for
    // (scripts/expert-placement.py --ts). Compared against the serve's -ts at
    // load so a stale artifact or a retuned -ts is visible - plan section 5.
    std::vector<double> member_shares;

    // per layer: experts per member in permuted order; member j owns permuted
    // positions [sum(counts[il][0..j-1]), sum(counts[il][0..j])). Empty for
    // unplaced layers. counts[il].size() == n_members for placed layers.
    std::vector<std::vector<int32_t> > counts;

    bool layer_placed(uint32_t il) const {
        return il < perm.size() && !perm[il].empty();
    }
};

// parse + validate the artifact at 'path' against the model shape and member
// count. Throws std::runtime_error naming the offending field on any mismatch
// (loud load-time consistency check - plan §3).
std::unique_ptr<llama_expert_placement> llama_expert_placement_load(
        const std::string & path, uint32_t n_layer, uint32_t n_expert, size_t n_members);

// the placed layer index for a routed-expert weight tensor name
// (`blk.<il>.ffn_{gate,up,gate_up,down}_exps.weight`), or -1 when the name is
// not one / the layer is unplaced. Shared by the model loader (permuted
// upload) and the meta split policy (llama-model.cpp).
int llama_expert_placement_layer_for(
        const llama_expert_placement * pl, const char * tensor_name);

// the dim-2 load permutation for a routed-expert weight tensor, or nullptr when
// the name is not a placed `blk.<il>.ffn_{gate,up,gate_up,down}_exps.weight`.
// Used by the model loader to read expert chunks in permuted (hottest-first)
// order so the meta buffer receives an already-permuted logical tensor.
const std::vector<int32_t> * llama_expert_placement_perm_for(
        const llama_expert_placement * pl, const char * tensor_name);

// TASKS #75: per-layer ownership tables consumed by build_moe_ffn (plan §2c).
// Both are registered MIRRORED with per-member CONTENTS (uploaded through
// ggml_backend_meta_tensor_set_member):
// remap[il]: I32 [n_expert], global expert id -> member-LOCAL slot (a benign
//            state lie - non-owned lanes are zeroed by the mask below).
// mask[il]:  F32 [n_expert], 1.0 owned / 0.0 not. Member masks sum to the
//            all-ones vector; PARTIAL enters the split derivation one step
//            later, via the name-tagged handle_bin_bcast rule on the masked
//            expert product ('ffn_moe_weighted_placed') - not via the table.
struct llama_expert_placement_tables {
    ggml_context_ptr        ctx;
    ggml_backend_buffer_ptr buf;

    std::vector<ggml_tensor *> remap; // indexed by il; nullptr = unplaced layer
    std::vector<ggml_tensor *> mask;
};

// create + upload the tables on the meta buffer type (shadows per member get
// their per-member contents via ggml_backend_meta_tensor_set_member)
std::unique_ptr<llama_expert_placement_tables> llama_expert_placement_create_tables(
        const llama_expert_placement & pl, ggml_backend_buffer_type_t meta_buft, size_t n_members);
