#pragma once

// TASKS #75: hot-expert placement - frequency-ranked whole-expert assignment of
// routed experts to meta members. Artifact generated by scripts/expert-placement.py
// from a #74 LLAMA_EXPERT_PROFILE histogram; enabled via
// LLAMA_META_EXPERT_PLACEMENT=<json> on tensor-split (meta) configs.
// Design + gates: docs/expert-placement-plan.md

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "ggml-cpp.h"

struct llama_expert_placement {
    std::string path;
    std::string model_name; // informational, from the artifact

    uint32_t n_layer  = 0;
    uint32_t n_expert = 0;

    // per layer: hottest-first permutation; perm[il][k] = ORIGINAL expert id at
    // permuted position k. Empty vector for layers without placement (dense or
    // never-routed layers in the profile).
    std::vector<std::vector<int32_t> > perm;

    // per layer: experts per member in permuted order; member j owns permuted
    // positions [sum(counts[il][0..j-1]), sum(counts[il][0..j])). Empty for
    // unplaced layers. counts[il].size() == n_members for placed layers.
    std::vector<std::vector<int32_t> > counts;

    // derived, per layer: original expert id -> owning member (-1 = unplaced layer)
    std::vector<std::vector<int32_t> > member_of;
    // derived, per layer: original expert id -> permuted position
    std::vector<std::vector<int32_t> > perm_pos;

    bool layer_placed(uint32_t il) const {
        return il < perm.size() && !perm[il].empty();
    }
};

// parse + validate the artifact at 'path' against the model shape and member
// count. Throws std::runtime_error naming the offending field on any mismatch
// (loud load-time consistency check - plan §3).
std::unique_ptr<llama_expert_placement> llama_expert_placement_load(
        const std::string & path, uint32_t n_layer, uint32_t n_expert, size_t n_members);

// the dim-2 load permutation for a routed-expert weight tensor, or nullptr when
// the name is not a placed `blk.<il>.ffn_{gate,up,gate_up,down}_exps.weight`.
// Used by the model loader to read expert chunks in permuted (hottest-first)
// order so the meta buffer receives an already-permuted logical tensor.
const std::vector<int32_t> * llama_expert_placement_perm_for(
        const llama_expert_placement * pl, const char * tensor_name);

// TASKS #75: per-layer ownership tables consumed by build_moe_ffn (plan §2c).
// remap[il]: I32 [n_expert], global expert id -> member-LOCAL slot (per-member
//            contents; MIRRORED split state - a benign lie, masked lanes only).
// mask[il]:  F32 [n_expert], 1.0 owned / 0.0 not (per-member contents; PARTIAL
//            split state - honest: member masks sum to the all-ones vector).
struct llama_expert_placement_tables {
    ggml_context_ptr        ctx;
    ggml_backend_buffer_ptr buf;

    std::vector<ggml_tensor *> remap; // indexed by il; nullptr = unplaced layer
    std::vector<ggml_tensor *> mask;
};

// create + upload the tables on the meta buffer type (shadows per member get
// their per-member contents via ggml_backend_meta_tensor_set_member)
std::unique_ptr<llama_expert_placement_tables> llama_expert_placement_create_tables(
        const llama_expert_placement & pl, ggml_backend_buffer_type_t meta_buft, size_t n_members);
